### ISSUE TITLE
KeyError: 'wm'

### ISSUE THREAD

**Issue by sando1234** [archcraft-os/archcraft-theme-manager#5]
When I try to start the theme manager I get an error

` Traceback (most recent call last):
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 587, in <module>
     ThemeManager().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 949, in _run_prepare
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 151, in on_start
     self.load_online()
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 207, in load_online
     Widget.wm = self.themes["Online"][theme]["wm"]
 KeyError: 'wm'`
 
Sorry for bad spelling I'm not a native Englisch speaker :D.

**Comment by T-Dynamos** [comment]
Closed with https://github.com/archcraft-os/archcraft-theme-manager/commit/c77c3ebd81fa92c079c2cf287c74dc925d7e6092
