### ISSUE TITLE
 UnboundLocalError: local variable 'folders' referenced before assignment

### ISSUE THREAD

**Issue by sando1234** [archcraft-os/archcraft-theme-manager#6]
When I try to start the theme manager I get an error

` Traceback (most recent call last):
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 615, in <module>
     ThemeManager().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 949, in _run_prepare
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 160, in on_start
     self.load_popular()
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 202, in load_popular
     in self.get_all_openbox_themes() + self.get_all_bspwm_themes()
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 488, in get_all_openbox_themes
     return folders
 UnboundLocalError: local variable 'folders' referenced before assignment`

Sorry for bad spelling I'm not a native Englisch speaker :D.
(Take 2)

**Comment by T-Dynamos** [comment]
Don't run it as root.

**Comment by sando1234** [comment]
Im running it as user :D

Here is more of the log:

`[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_23-02-19_0.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [KivyMD      ] Release 1.1.1 (installed at "/opt/archcraft-theme-manager/archcraft-theme-manager/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 22.3.4'>
[INFO   ] [GL          ] OpenGL vendor <b'AMD'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.1.12-x64v3-xanmod1)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
[WARNING] [archcraft-theme-manager ] not found /home/user/.config/archcraft-theme-manager/config.ini
[WARNING] [archcraft-theme-manager ] Reading default config file
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 615, in <module>
     ThemeManager().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 949, in _run_prepare
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 160, in on_start
     self.load_popular()
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 202, in load_popular
     in self.get_all_openbox_themes() + self.get_all_bspwm_themes()
   File "/opt/archcraft-theme-manager/archcraft-theme-manager/main.py", line 488, in get_all_openbox_themes
     return folders
 UnboundLocalError: local variable 'folders' referenced before assignment`

**Comment by T-Dynamos** [comment]
Please send output of:
```bash
ls /home/<username>/.config/openbox-themes/themes/
```
(Use your username)

**Comment by sando1234** [comment]
`ls: cannot access '/home/sandows/.config/openbox-themes/themes/': No such file or directory`

This folder doesnt exist
(I'm using the wayland version)

**Comment by T-Dynamos** [comment]
Are you using archcraft?
Is `archcraft-openbox` installed or update to latest version?

**Comment by sando1234** [comment]
It is not installed

I'm using the Archcraft Premium Wayland version.

**Comment by T-Dynamos** [comment]
Yes you may try install `archcraft-openbox` then try running it.

**Comment by sando1234** [comment]
ice installed both the `archcraft-openbox` and the `archcraft-bspwm` packages and now it works :D, Thanks.

You could install them by default.
