### ISSUE TITLE
Error while executing the script

### ISSUE THREAD

**Issue by Azathoth-11** [archcraft-os/archcraft-theme-manager#7]
Traceback (most recent call last):
   File "/home/user/Downloads/archcraft-theme-manager/archcraft-theme-manager/main.py", line 13, in <module>
     from kivymd.theming import ThemableBehavior
   File "/home/user/.local/lib/python3.10/site-packages/kivymd/__init__.py", line 34, in <module>
     kivy.require("2.2.0")
   File "/home/user/.local/lib/python3.10/site-packages/kivy/__init__.py", line 130, in require
     raise Exception('The version of Kivy installed on this system '
 Exception: The version of Kivy installed on this system is too old. (You have 2.1.0, but the application requires 2.2.0)

**Comment by T-Dynamos** [comment]
```
pip3 install kivy --pre --index-url  https://kivy.org/downloads/simple/ --upgrade

```
The error is because of an old Kivy version. Executing the above command would do the job. This update has also been added to the readme.
